apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-jenkins-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-jenkins-notifier
  template:
    metadata:
      labels:
        app: github-jenkins-notifier
    spec:
      containers:
      - name: github-jenkins-notifier
        image: $DOCKER_IMAGE
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          value: $AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          value: $AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: $AWS_REGION
        - name: JENKINS_BASE_URL
          value: $JENKINS_BASE_URL
        - name: JENKINS_TOKEN
          value: $JENKINS_TOKEN
        - name: GITHUB_USER
          value: $GITHUB_USER
        - name: SQS_QUEUE_URL
          value: $SQS_QUEUE_URL
        